# Generated by Django 3.2.5 on 2021-07-25 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
