# Generated by Django 3.2.5 on 2021-07-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_assignee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
