# Generated by Django 3.2.5 on 2021-07-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='author',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tag',
        ),
    ]
