# Generated by Django 3.2.5 on 2021-07-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20210726_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
