# Generated by Django 3.2.5 on 2021-07-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
