# Generated by Django 3.2.6 on 2021-08-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0015_alter_comment_issue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(blank=True, choices=[('highest', 'highest'), ('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('todo', 'todo'), ('inprogress', 'inprogress'), ('open', 'open'), ('closed', 'closed'), ('reopened', 'reopened'), ('resolved', 'resolved')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(blank=True, choices=[('bug', 'bug'), ('tache', 'tache'), ('amelioration', 'amelioration')], default='bug', max_length=20),
        ),
    ]
