# Generated by Django 3.2.5 on 2021-07-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='inviter',
        ),
    ]
